### ISSUE TITLE
How do you install this?

### ISSUE THREAD

**Issue by sebas1111111** [fabSchneider/fab.uitk-runtime-dropdown#3]
I've tried using the package manager with this url (https://github.com/fabSchneider/fab.uitk-runtime-dropdown.git) and it says:

Unable to add package [https://github.com/fabSchneider/fab.uitk-runtime-dropdown.git]:
  [https://github.com/fabSchneider/fab.uitk-runtime-dropdown.git] does not point to a valid package. No package manifest was found.

I've also tried copying the contents Packages folder from the zip file into the Packages folder of the project. That gives tons of errors (using Unity 2022.3)

**Comment by fabSchneider** [comment]
Try adding the upm branch with the package manager instead. To do so add a #upm after the url like so: 
https://github.com/fabSchneider/fab.uitk-runtime-dropdown.git#upm

**Comment by sebas1111111** [comment]
I'm getting 93 errors, just like when I manually added the package to the project. All of them seem to be referring to the syntax. Maybe I'm missing some dependency?

Couple examples:
`Library\PackageCache\com.fab.uitk-runtime-dropdown@bcdde6bd1d\Runtime\Dropdown.cs(491,49): error CS1525: Invalid expression term ')'`
`Library\PackageCache\com.fab.uitk-runtime-dropdown@bcdde6bd1d\Runtime\Dropdown.cs(491,49): error CS1002: ; expected`

**Comment by sebas1111111** [comment]
That first error, for instance, points to this:

![image](https://github.com/fabSchneider/fab.uitk-runtime-dropdown/assets/5789040/28d19bd7-0dbe-462f-9042-b9908b6b620d)

**Comment by fabSchneider** [comment]
This is indeed a bug. Thanks for the info. 
It is now fixed and works for 2022.3.

**Comment by FreyaHolmer** [comment]
I'm having a similar issue in unity 6, idk if I'm doing something wrong?

This is when I try adding using the git url option:
```
[Package Manager Window] Error adding package: https://github.com/fabSchneider/fab.uitk-runtime-dropdown#upm.
Unable to add package [https://github.com/fabSchneider/fab.uitk-runtime-dropdown#upm]:
  Package name 'https://github.com/fabSchneider/fab.uitk-runtime-dropdown#upm' is invalid.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()```

**Comment by fabSchneider** [comment]
> I'm having a similar issue in unity 6, idk if I'm doing something wrong?

You are missing the `.git` in the git url. 
This url should work. 
`https://github.com/fabSchneider/fab.uitk-runtime-dropdown.git#upm`

I will add an install section in the readme for clarity.
