### ISSUE TITLE
Update to new unity 6 breaks menu closing + fix

### ISSUE THREAD

**Issue by wybo** [fabSchneider/fab.uitk-runtime-dropdown#4]
Had to replace line 492 in Dropdown.cs as follows:

//if (evt.propagationPhase == PropagationPhase.AtTarget)
if (evt.currentTarget == evt.target)

Due to ended support for AtTarget
https://docs.unity3d.com/6000.0/Documentation/Manual/UpgradeGuide20232.html

**Comment by fabSchneider** [comment]
The issue should have been fixed in the most recent version 1.0.1
