### ISSUE TITLE
Make menu buttons opened-colored when their menu is open + fix

### ISSUE THREAD

**Issue by wybo** [fabSchneider/fab.uitk-runtime-dropdown#7]
Add this to Runtime/Dropdown.cs to have the button used to open the menu also show the color for a menu item whose sub-menu is open.

```
        Button button;

        public void Open(DropdownMenu menu, Button theButton, EventBase evt = null) {
            button = theButton;
            Open(menu, button.worldBound, evt);
            OnToggle();
        }

        public bool IsOpen() {
            return (dropdownLayer.parent != null);
        }

        void OnToggle() {
            if (button == null) {
                return;
            }

            if (IsOpen()) {
                button.AddToClassList(openedItemClassname);
            } else {
                button.RemoveFromClassList(openedItemClassname);
            }
        }
```

Then also add the OnToggle() call to close:

```
        /// <summary>
        /// Closes the dropdown.
        /// </summary>
        public void Close()
        {
            if (rootMenu != null)
            {
                rootMenu.CloseSubMenus();
            }
            dropdownLayer.RemoveFromHierarchy();
            OnToggle(); // <--- HERE
        }
```

You can then color style it with the same ".fab-dropdown__sub-menu-item--opened" USS tag (make sure to put it after any button styling).

**Comment by fabSchneider** [comment]
Thanks for the suggestion! 
I pushed a solution that adds the uss class `fab-dropdown-target--open` to the `EventBase` target passed with the `Open` method. You can now simply pass the event from a clickable element and it will automatically set the right target rect as well. Check out the sample for more info.
